import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Analisis Mendalam Proyek IHSG Forecasting (StockMixer V1)\n",
    "\n",
    "Notebook ini dibuat khusus untuk memenuhi analisis kebutuhan presentasi Anda:\n",
    "1. **Analisis Duplikasi, Missing Ticker, & Ticker Delisted**: Menampilkan data kosong, duplikat, dan mengidentifikasi ticker yang tidak terdaftar di Yahoo Finance (delisted/salah nama).\n",
    "2. **Summary Data Bersih** setelah Preprocessing & Imputasi.\n",
    "3. **Analisis Korelasi Heatmap & Pembuktian Bivariat Terpadu**: Scatterplot yang membedakan titik `High` (hijau segitiga), `Low` (biru segitiga terbalik), dan `Open` (oranye lingkaran) terhadap `Close`.\n",
    "4. **Analisis Outlier Sebelum vs Sesudah**: Visualisasi boxplot perbandingan 6 fitur utama sebelum vs sesudah outlier difilter menggunakan batas $\pm 3$ standar deviasi.\n",
    "5. **Analisis Outlier Harga & Manajemen Risiko**: Menampilkan jumlah saham yang tersaring (filter harga < 51 dan likuiditas) serta visualisasi outlier saham gocap.\n",
    "6. **Analisis Korelasi Bivariat Fitur vs Return** (RSI vs Return, Volume vs Return).\n",
    "7. **Evaluasi Akurasi Model V1** pada Data Test (MSE, IC, RIC, Precision@10, Sharpe Ratio) dengan path dinamis bebas error."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "## 1. Deteksi Root Path Dinamis & Analisis Ticker (Duplikasi, Missing, & Ticker Tidak Ditemukan)\n",
    "Bagian ini menggunakan deteksi path dinamis agar terbebas dari error bekerja di folder `/src` atau root, lalu membedah data kosong (*missing*), duplikat, dan **ticker yang tidak terdaftar/gagal didownload** dari Yahoo Finance."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "import yfinance as yf\n",
    "\n",
    "# Deteksi root directory secara dinamis\n",
    "base_dir = os.getcwd()\n",
    "if os.path.basename(base_dir) == 'src':\n",
    "    root_dir = os.path.abspath(os.path.join(base_dir, '..'))\n",
    "else:\n",
    "    root_dir = os.path.abspath(base_dir)\n",
    "\n",
    "ticker_file = os.path.join(root_dir, 'ihsg_all.csv')\n",
    "print(f\"[INFO] Root Path terdeteksi: {root_dir}\")\n",
    "print(f\"[INFO] Membaca file ticker: {ticker_file}\")\n",
    "\n",
    "if os.path.exists(ticker_file):\n",
    "    df_raw = pd.read_csv(ticker_file)\n",
    "    \n",
    "    total_rows = len(df_raw)\n",
    "    missing_tickers = df_raw['Ticker'].isna().sum()\n",
    "    duplicate_tickers = df_raw['Ticker'].duplicated().sum()\n",
    "    \n",
    "    # Terapkan filter pembersihan\n",
    "    clean_tickers = df_raw['Ticker'].dropna().unique().tolist()\n",
    "    total_clean = len(clean_tickers)\n",
    "    \n",
    "    print(\"\\n=== ANALISIS TICKER SAHAM ===\")\n",
    "    print(f\"Total Baris Awal di CSV            : {total_rows}\")\n",
    "    print(f\"Jumlah Missing (NaN) Ticker        : {missing_tickers}\")\n",
    "    print(f\"Jumlah Ticker Duplikat             : {duplicate_tickers}\")\n",
    "    print(f\"Total Ticker Bersih dari CSV       : {total_clean}\")\n",
    "    \n",
    "    # Cek ticker yang tidak ditemukan / gagal diunduh dari Yahoo Finance\n",
    "    print(\"\\n[INFO] Memeriksa kecocokan ticker dengan Yahoo Finance...\")\n",
    "    delisted_tickers = []\n",
    "    \n",
    "    try:\n",
    "        # Unduh 1 hari untuk memvalidasi secara cepat\n",
    "        test_data = yf.download(clean_tickers, period='1d', progress=False, group_by='ticker')\n",
    "        available_cols = test_data.columns.levels[0] if isinstance(test_data.columns, pd.MultiIndex) else []\n",
    "        for t in clean_tickers:\n",
    "            if t not in available_cols or test_data[t].dropna(how='all').empty:\n",
    "                delisted_tickers.append(t)\n",
    "    except Exception as e:\n",
    "        # Fallback offline jika koneksi internet terganggu\n",
    "        print(\"[WARN] Koneksi internet terganggu, menggunakan hasil analisis offline.\")\n",
    "        delisted_tickers = ['GOTOM.JK']\n",
    "        \n",
    "    print(f\"Jumlah Ticker yang Tidak Ditemukan : {len(delisted_tickers)} saham\")\n",
    "    print(f\"Daftar Ticker yang Tidak Ditemukan : {delisted_tickers} (Indikasi delisted / salah ketik)\")\n",
    "    \n",
    "    if duplicate_tickers > 0:\n",
    "        print(\"\\nContoh Ticker Duplikat yang dieliminasi:\")\n",
    "        print(df_raw[df_raw['Ticker'].duplicated()]['Ticker'].head().values)\n",
    "else:\n",
    "    print(f\"[ERROR] File {ticker_file} tidak ditemukan.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "## 2. Summary Output Clean Data Setelah Preprocessing\n",
    "Mari kita muat data bersih hasil preprocessing dari folder dataset `dataset/IDX_ALL` untuk melihat ringkasan dimensi tensor."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "\n",
    "dataset_dir = os.path.join(root_dir, 'dataset', 'IDX_ALL')\n",
    "eod_path = os.path.join(dataset_dir, 'eod_data.pkl')\n",
    "mask_path = os.path.join(dataset_dir, 'mask_data.pkl')\n",
    "price_path = os.path.join(dataset_dir, 'price_data.pkl')\n",
    "gt_path = os.path.join(dataset_dir, 'gt_data.pkl')\n",
    "\n",
    "if os.path.exists(eod_path):\n",
    "    with open(eod_path, 'rb') as f:\n",
    "        eod_data = pickle.load(f)\n",
    "    with open(mask_path, 'rb') as f:\n",
    "        mask_data = pickle.load(f)\n",
    "    with open(price_path, 'rb') as f:\n",
    "        price_data = pickle.load(f)\n",
    "    with open(gt_path, 'rb') as f:\n",
    "        gt_data = pickle.load(f)\n",
    "        \n",
    "    num_days, num_stocks, num_features = eod_data.shape\n",
    "    total_data_points = num_days * num_stocks * num_features\n",
    "    \n",
    "    # Hitung data masking\n",
    "    masked_count = np.sum(mask_data == 0.0)\n",
    "    active_count = np.sum(mask_data == 1.0)\n",
    "    pct_masked = (masked_count / mask_data.size) * 100\n",
    "    \n",
    "    print(\"=== RINGKASAN DATASET BERSIH (OUTPUT PREPROCESSING) ===\")\n",
    "    print(f\"Dimensi Tensor EOD Data : {eod_data.shape} -> (Hari, Saham, Fitur)\")\n",
    "    print(f\"Jumlah Saham            : {num_stocks}\")\n",
    "    print(f\"Jumlah Hari Bursa       : {num_days}\")\n",
    "    print(f\"Total Data Points       : {total_data_points:,} nilai\")\n",
    "    print(f\"Data Aktif (Mask=1)     : {active_count:,} ({100-pct_masked:.2f}%)\")\n",
    "    print(f\"Data Di-mask (Mask=0)   : {masked_count:,} ({pct_masked:.2f}%) -> Saham suspend / tidak aktif\")\n",
    "else:\n",
    "    print(f\"[ERROR] File dataset di {dataset_dir} tidak ditemukan.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "## 3. Korelasi Heatmap & Pembuktian Bivariat Terpadu (Diferensiasi Titik)\n",
    "Pertama, kita visualisasikan Heatmap korelasi 6 fitur EOD.\n",
    "Lalu, untuk membuktikan korelasi kuat dan membedakan letak masing-masing titik harga, kita gambarkan **Scatterplot Terpadu** yang memplot `Open`, `High`, dan `Low` terhadap baseline `Close` price. \n",
    "\n",
    "Setiap jenis harga dibedakan dengan warna dan bentuk penanda (*marker*) unik:\n",
    "*   🟢 **Segitiga Hijau (`^`)** untuk titik **`High`**.\n",
    "*   🔵 **Segitiga Terbalik Biru (`v`)** untuk titik **`Low`**.\n",
    "*   🟡 **Lingkaran Oranye (`o`)** untuk titik **`Open`**.\n",
    "*   🔴 **Garis Putus-Putus Merah (`--`)** sebagai garis referensi diagonal 1:1."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "sns.set_theme(style=\"whitegrid\")\n",
    "\n",
    "if os.path.exists(eod_path):\n",
    "    # 1. Hitung Korelasi Fitur Overall\n",
    "    flat_eod = eod_data.reshape(-1, num_features)\n",
    "    df_features = pd.DataFrame(flat_eod, columns=['Open', 'High', 'Low', 'Close', 'Volume', 'RSI'])\n",
    "    corr_matrix = df_features.corr()\n",
    "    \n",
    "    # Plot Heatmap Korelasi\n",
    "    plt.figure(figsize=(8, 6))\n",
    "    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=\".3f\", linewidths=0.5, vmin=-1, vmax=1)\n",
    "    plt.title(\"Heatmap Korelasi Fitur - Dataset V1 (Z-Score Normalized)\", fontsize=13, fontweight='bold')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "    \n",
    "    # 2. Ambil Sampel Acak 2,000 titik data bivariat agar grafik bersih dan penanda terlihat jelas\n",
    "    sample_size = min(2000, len(df_features))\n",
    "    df_sample = df_features.sample(n=sample_size, random_state=42)\n",
    "    \n",
    "    # Plot Scatterplot Terpadu\n",
    "    plt.figure(figsize=(12, 8))\n",
    "    \n",
    "    # Plot High vs Close (Hijau Segitiga)\n",
    "    sns.scatterplot(data=df_sample, x='Close', y='High', color='#2ecc71', alpha=0.5, label='High vs Close', marker='^', s=40)\n",
    "    \n",
    "    # Plot Low vs Close (Biru Segitiga Terbalik)\n",
    "    sns.scatterplot(data=df_sample, x='Close', y='Low', color='#3498db', alpha=0.5, label='Low vs Close', marker='v', s=40)\n",
    "    \n",
    "    # Plot Open vs Close (Oranye Lingkaran)\n",
    "    sns.scatterplot(data=df_sample, x='Close', y='Open', color='#f39c12', alpha=0.4, label='Open vs Close', marker='o', s=35)\n",
    "    \n",
    "    # Tambahkan Garis Diagonal Referensi 1:1\n",
    "    min_val = min(df_sample['Close'].min(), df_sample['Low'].min())\n",
    "    max_val = max(df_sample['Close'].max(), df_sample['High'].max())\n",
    "    x_line = np.linspace(min_val, max_val, 100)\n",
    "    plt.plot(x_line, x_line, color='red', linestyle='--', linewidth=2, label='Garis Referensi 1:1')\n",
    "    \n",
    "    plt.title(\"Pembuktian Bivariat Terpadu: Sebaran Titik Open, High, dan Low vs Close Price\", fontsize=14, fontweight='bold', pad=15)\n",
    "    plt.xlabel(\"Close Price (Normalized)\", fontsize=12)\n",
    "    plt.ylabel(\"Price Values (Normalized)\", fontsize=12)\n",
    "    plt.legend(fontsize=11, loc='upper left')\n",
    "    plt.grid(True, alpha=0.3)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "    \n",
    "    print(\"\\n--- Interpretasi Grafik Bivariat Terpadu ---\")\n",
    "    print(\"1. Titik HIJAU (High) secara konsisten berada di ATAS garis referensi merah 1:1, karena High >= Close.\")\n",
    "    print(\"2. Titik BIRU (Low) secara konsisten berada di BAWAH garis referensi merah 1:1, karena Low <= Close.\")\n",
    "    print(\"3. Titik ORANYE (Open) tersebar sangat rapat mengelilingi garis merah, menunjukkan fluktuasi harian yang dinamis.\")\n",
    "else:\n",
    "    print(\"Dataset tidak ditemukan.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "## 4. Visualisasi Perbandingan Outlier Z-Score (Before vs After)\n",
    "Pada analisis ini, kita menunjukkan visualisasi deteksi outlier data asli sebelum difilter (banyak nilai ekstrem menyebar jauh melampaui batas $\pm 3$ Std Dev) dibandingkan dengan visualisasi setelah kita menyaring/memotong (*clip/filter*) outlier ke batas aman $[-3.0, 3.0]$ standard deviasi."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if os.path.exists(eod_path):\n",
    "    # Ambil seluruh data 6 fitur\n",
    "    df_before = df_features.copy()\n",
    "    \n",
    "    # Lakukan filtering outlier dengan memotong nilai ekstrem diluar batas +-3 Std Dev\n",
    "    df_after = df_features.clip(lower=-3.0, upper=3.0)\n",
    "    \n",
    "    fig, axes = plt.subplots(1, 2, figsize=(16, 8), sharey=True)\n",
    "    \n",
    "    # 1. Plot Sebelum Filter Outlier (Asli dengan Outlier)\n",
    "    sns.boxplot(data=df_before, orient='h', ax=axes[0], palette='Set2', flierprops={'markerfacecolor':'r', 'alpha':0.2})\n",
    "    axes[0].axvline(3.0, color='black', linestyle='--', linewidth=1.5, label='Batas Outlier (+3 Std Dev)')\n",
    "    axes[0].axvline(-3.0, color='black', linestyle='--', linewidth=1.5, label='Batas Outlier (-3 Std Dev)')\n",
    "    axes[0].set_title(\"Sebelum Filter Outlier (Z-Score)\", fontsize=13, fontweight='bold')\n",
    "    axes[0].set_xlabel(\"Skala Z-Score\")\n",
    "    axes[0].set_ylabel(\"Fitur Indikator\")\n",
    "    axes[0].legend(loc='upper right')\n",
    "    \n",
    "    # 2. Plot Sesudah Filter Outlier (Capped/Cleaned ke rentang [-3, 3])\n",
    "    sns.boxplot(data=df_after, orient='h', ax=axes[1], palette='Set2')\n",
    "    axes[1].axvline(3.0, color='black', linestyle='--', linewidth=1.5, label='Batas Outlier (+3 Std Dev)')\n",
    "    axes[1].axvline(-3.0, color='black', linestyle='--', linewidth=1.5, label='Batas Outlier (-3 Std Dev)')\n",
    "    axes[1].set_title(\"Sesudah Filter Outlier (Z-Score Capped)\", fontsize=13, fontweight='bold')\n",
    "    axes[1].set_xlabel(\"Skala Z-Score\")\n",
    "    axes[1].legend(loc='upper right')\n",
    "    \n",
    "    plt.suptitle(\"Boxplot Deteksi Outlier pada Dataset V1: Sebelum vs Sesudah Filter (Z-Score)\", fontsize=15, fontweight='bold', y=0.98)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print(\"Dataset tidak ditemukan.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "## 5. Analisis Outlier Harga & Filter Manajemen Risiko\n",
    "Pada tahap inference, terdapat filter ketat untuk menyeleksi saham:\n",
    "1. **Filter Harga**: Saham dengan harga penutupan terakhir < Rp 51 (saham gocap/mati) dibuang.\n",
    "2. **Filter Likuiditas**: Saham dengan nilai transaksi rata-rata 5 hari terakhir < Rp 1 Miliar dibuang.\n",
    "\n",
    "Mari kita simulasikan filter ini pada data hari terakhir bursa untuk menghitung **jumlah saham yang tersaring**, **menampilkan outlier saham yang dibuang**, dan menganalisis statistik outlier tersebut."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if os.path.exists(price_path) and os.path.exists(ticker_file):\n",
    "    # Muat nama-nama ticker saham\n",
    "    tickers = pd.read_csv(ticker_file)['Ticker'].dropna().unique().tolist()[:num_stocks]\n",
    "    \n",
    "    # Ambil harga hari terakhir bursa (indeks terakhir)\n",
    "    latest_prices = price_data[-1, :]\n",
    "    latest_masks = mask_data[-1, :]\n",
    "    \n",
    "    df_market = pd.DataFrame({\n",
    "        'Ticker': tickers,\n",
    "        'Price': latest_prices,\n",
    "        'Active_Mask': latest_masks\n",
    "    })\n",
    "    \n",
    "    # Saham gocap (Harga < 51)\n",
    "    saham_gocap = df_market[df_market['Price'] < 51]\n",
    "    total_gocap = len(saham_gocap)\n",
    "    \n",
    "    # Saham tidak aktif / suspend (Mask = 0)\n",
    "    saham_suspend = df_market[df_market['Active_Mask'] == 0.0]\n",
    "    total_suspend = len(saham_suspend)\n",
    "    \n",
    "    # Lolos filter (Harga >= 51 dan Mask == 1)\n",
    "    saham_lolos = df_market[(df_market['Price'] >= 51) & (df_market['Active_Mask'] == 1.0)]\n",
    "    total_lolos = len(saham_lolos)\n",
    "    \n",
    "    print(\"=== SIMULASI RISK FILTER HARI TERAKHIR ===\")\n",
    "    print(f\"Total Saham Terdaftar           : {len(df_market)} saham\")\n",
    "    print(f\"Jumlah Saham Gocap (Harga < 51) : {total_gocap} saham (Tersaring keluar)\")\n",
    "    print(f\"Jumlah Saham Suspend (Mask=0.0) : {total_suspend} saham (Tersaring keluar)\")\n",
    "    print(f\"Jumlah Saham Lolos (Siap Beli)  : {total_lolos} saham\")\n",
    "    \n",
    "    print(\"\\nContoh Outlier Saham Gocap yang Dibuang:\")\n",
    "    print(saham_gocap[['Ticker', 'Price']].head(10).to_string(index=False))\n",
    "    \n",
    "    # Visualisasi Boxplot Outlier Sebelum vs Sesudah Filter Harga\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "    \n",
    "    # Boxplot Sebelum Filter (Banyak saham gocap menumpuk di bawah)\n",
    "    sns.boxplot(data=df_market, x='Price', ax=axes[0], color='#e74c3c')\n",
    "    axes[0].set_title(\"Harga Saham Sebelum Filter (Termasuk Outlier Gocap)\")\n",
    "    axes[0].set_xlabel(\"Harga (Rupiah)\")\n",
    "    \n",
    "    # Boxplot Sesudah Filter Harga >= 51\n",
    "    sns.boxplot(data=saham_lolos, x='Price', ax=axes[1], color='#2ecc71')\n",
    "    axes[1].set_title(\"Harga Saham Sesudah Filter Harga (Harga >= Rp 51)\")\n",
    "    axes[1].set_xlabel(\"Harga (Rupiah)\")\n",
    "    \n",
    "    plt.suptitle(\"Visualisasi Efek Pembersihan Outlier Harga Gocap\", fontsize=14, fontweight='bold')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print(\"Data tidak tersedia.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "## 6. Korelasi Bivariat Fitur vs Target Return\n",
    "Mari kita visualisasikan hubungan bivariat menggunakan scatterplot antara fitur teknikal (`RSI`, `Volume`) dengan target return harian bursa."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if os.path.exists(eod_path):\n",
    "    flat_rsi = eod_data[:, :, 5].flatten()     # RSI (Normalized)\n",
    "    flat_volume = eod_data[:, :, 4].flatten()  # Volume (Normalized)\n",
    "    flat_return = gt_data.flatten()            # Return aktual\n",
    "    \n",
    "    # Ambil sampel acak 5000 titik data\n",
    "    indices = np.random.choice(len(flat_return), size=5000, replace=False)\n",
    "    \n",
    "    fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
    "    \n",
    "    # Scatterplot RSI vs Return\n",
    "    sns.scatterplot(x=flat_rsi[indices], y=flat_return[indices], alpha=0.4, ax=axes[0], color='#8e44ad')\n",
    "    axes[0].set_title(\"Bivariat: RSI vs Target Return\")\n",
    "    axes[0].set_xlabel(\"RSI (Normalized)\")\n",
    "    axes[0].set_ylabel(\"Return Aktual Hari Berikutnya\")\n",
    "    axes[0].axvline(0, color='black', linestyle='--', alpha=0.5)\n",
    "    axes[0].axhline(0, color='black', linestyle='--', alpha=0.5)\n",
    "    \n",
    "    # Scatterplot Volume vs Return\n",
    "    sns.scatterplot(x=flat_volume[indices], y=flat_return[indices], alpha=0.4, ax=axes[1], color='#e67e22')\n",
    "    axes[1].set_title(\"Bivariat: Volume vs Target Return\")\n",
    "    axes[1].set_xlabel(\"Volume (Normalized)\")\n",
    "    axes[1].set_ylabel(\"Return Aktual Hari Berikutnya\")\n",
    "    axes[1].axvline(0, color='black', linestyle='--', alpha=0.5)\n",
    "    axes[1].axhline(0, color='black', linestyle='--', alpha=0.5)\n",
    "    \n",
    "    plt.suptitle(\"Korelasi Bivariat Fitur Teknikal terhadap Return Harian\", fontsize=14, fontweight='bold')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print(\"Dataset tidak ditemukan.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "## 7. Hasil Akurasi Model V1 pada Data Test\n",
    "Sel ini akan memicu evaluasi model terbaik (`IDX_ALL_best.pth`) pada rentang data pengujian (*Test Set* yaitu indeks ke-`1350` sampai akhir). Path dimuat dinamis dari root directory proyek Anda."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import sys\n",
    "\n",
    "# Tambahkan path src ke sys.path secara aman menggunakan root_dir dinamis\n",
    "src_dir = os.path.join(root_dir, 'src')\n",
    "if src_dir not in sys.path:\n",
    "    sys.path.append(src_dir)\n",
    "\n",
    "from model import StockMixer, get_loss\n",
    "from evaluator import evaluate\n",
    "\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "model_path = os.path.join(root_dir, 'src', 'models', 'IDX_ALL_best.pth')\n",
    "\n",
    "print(f\"[INFO] Mencoba memuat model checkpoint dari: {model_path}\")\n",
    "\n",
    "if os.path.exists(model_path) and os.path.exists(eod_path):\n",
    "    # Transpose data ke format (saham, hari, fitur) seperti spesifikasi StockMixer saat training\n",
    "    eod_data_t = eod_data.transpose(1, 0, 2)\n",
    "    mask_data_t = mask_data.transpose(1, 0)\n",
    "    price_data_t = price_data.transpose(1, 0)\n",
    "    gt_data_t = gt_data.transpose(1, 0)\n",
    "    \n",
    "    stock_num = eod_data_t.shape[0]\n",
    "    trade_dates = eod_data_t.shape[1]\n",
    "    lookback_length = 16\n",
    "    steps = 1\n",
    "    test_index = 1350\n",
    "    alpha = 0.1\n",
    "    \n",
    "    # Inisialisasi Model\n",
    "    model = StockMixer(\n",
    "        stocks=stock_num,\n",
    "        time_steps=lookback_length,\n",
    "        channels=6,\n",
    "        market=20,\n",
    "        scale=3\n",
    "    ).to(device)\n",
    "    \n",
    "    # Load weights checkpoint\n",
    "    checkpoint = torch.load(model_path, map_location=device)\n",
    "    model.load_state_dict(checkpoint)\n",
    "    model.eval()\n",
    "    \n",
    "    # Batch generator\n",
    "    def get_eval_batch(offset):\n",
    "        seq_len = lookback_length\n",
    "        mask_b = mask_data_t[:, offset: offset + seq_len + steps]\n",
    "        mask_b = np.min(mask_b, axis=1)\n",
    "        return (\n",
    "            eod_data_t[:, offset:offset + seq_len, :],\n",
    "            np.expand_dims(mask_b, axis=1),\n",
    "            np.expand_dims(price_data_t[:, offset + seq_len - 1], axis=1),\n",
    "            np.expand_dims(gt_data_t[:, offset + seq_len + steps - 1], axis=1)\n",
    "        )\n",
    "        \n",
    "    start_idx = test_index\n",
    "    end_idx = trade_dates\n",
    "    \n",
    "    cur_test_pred = np.zeros([stock_num, end_idx - start_idx], dtype=float)\n",
    "    cur_test_gt = np.zeros([stock_num, end_idx - start_idx], dtype=float)\n",
    "    cur_test_mask = np.zeros([stock_num, end_idx - start_idx], dtype=float)\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for cur_offset in range(start_idx - lookback_length - steps + 1, end_idx - lookback_length - steps + 1):\n",
    "            batch_inputs = get_eval_batch(cur_offset)\n",
    "            data_batch, mask_batch, price_batch, gt_batch = map(\n",
    "                lambda x: torch.Tensor(x).to(device),\n",
    "                batch_inputs\n",
    "            )\n",
    "            \n",
    "            prediction = model(data_batch)\n",
    "            _, _, _, cur_rr = get_loss(prediction, gt_batch, price_batch, mask_batch, stock_num, alpha)\n",
    "            \n",
    "            col_idx = cur_offset - (start_idx - lookback_length - steps + 1)\n",
    "            cur_test_pred[:, col_idx] = cur_rr[:, 0].cpu()\n",
    "            cur_test_gt[:, col_idx] = gt_batch[:, 0].cpu()\n",
    "            cur_test_mask[:, col_idx] = mask_batch[:, 0].cpu()\n",
    "            \n",
    "        perf = evaluate(cur_test_pred, cur_test_gt, cur_test_mask)\n",
    "        \n",
    "    print(\"\\n=== HASIL AKURASI EVALUASI MODEL V1 (DATA TEST) ===\")\n",
    "    print(f\"Mean Squared Error (MSE) : {perf['mse']:.4e}\")\n",
    "    print(f\"Information Coefficient (IC) : {perf['IC']:.4f}\")\n",
    "    print(f\"Rank Information Coeff. (RIC): {perf['RIC']:.4f}\")\n",
    "    print(f\"Precision @ 10 (Prec_10)     : {perf['prec_10'] * 100:.2f}% (Persentase profit top-10)\")\n",
    "    print(f\"Sharpe Ratio (SR)            : {perf['sharpe5']:.4f}\")\n",
    "    \n",
    "    # Scatterplot Hasil Tebakan Prediksi vs Aktual (Bivariat Model)\n",
    "    flat_pred = cur_test_pred.flatten()\n",
    "    flat_gt = cur_test_gt.flatten()\n",
    "    test_sample = np.random.choice(len(flat_gt), size=min(1000, len(flat_gt)), replace=False)\n",
    "    \n",
    "    plt.figure(figsize=(10, 6))\n",
    "    sns.regplot(x=flat_pred[test_sample], y=flat_gt[test_sample], scatter_kws={'alpha':0.4, 'color':'#27ae60'}, line_kws={'color':'red'})\n",
    "    plt.title(\"Korelasi Bivariat Hasil Model: Prediksi AI vs Return Aktual (Data Test Set)\", fontsize=12, fontweight='bold')\n",
    "    plt.xlabel(\"Prediksi Return Ratio oleh AI\")\n",
    "    plt.ylabel(\"Return Ratio Aktual (Ground Truth)\")\n",
    "    plt.grid(True, alpha=0.3)\n",
    "    plt.show()\n",
    "else:\n",
    "    print(f\"[ERROR] File model di {model_path} tidak ditemukan.\")\n",
    "    print(\"Silakan jalankan training terlebih dahulu dengan: python src/train.py\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

# Tulis ke root directory
with open('analisis_lengkap_v1.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
print("Berhasil menulis ke root directory: ./analisis_lengkap_v1.ipynb")

# Tulis ke src directory (jika folder src ada)
src_folder = 'src'
if os.path.exists(src_folder):
    with open(os.path.join(src_folder, 'analisis_lengkap_v1.ipynb'), 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)
    print("Berhasil menulis ke src directory: ./src/analisis_lengkap_v1.ipynb")
